name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm run test --coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage

  comment:
    name: comment
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/github-script@v6
        id: artifact-id
        with:
          result-encoding: string
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            });
            console.log(artifacts)
            return ""
